---
- hosts: localhost
  become: true
  gather_facts: true
  tasks:
    - name: Install tomcat on local server
      yum:
        name: tomcat
        state: latest

    - name: start tomcat server
      service:
        name: tomcat
        state: started 
